version: '3'

services:
  app:
    build: .
    ports:
      - "3000:5001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

